name: guitartuner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  wave: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/headstock.png
    - assets/sounds/HighE.mp3
    - assets/sounds/B.mp3
    - assets/sounds/G.mp3
    - assets/sounds/D.mp3
    - assets/sounds/A.mp3
    - assets/sounds/LowE.mp3
    - assets/songs/
    - assets/chords/c.png
    - assets/chords/d.png
    - assets/chords/dm.png
    - assets/chords/e.png
    - assets/chords/em.png
    - assets/chords/f.png
    - assets/chords/g.png
    - assets/chords/a.png
    - assets/chords/am.png
    - assets/chords/b.png
