name: guitartuner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  wave: ^0.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/headstock.png

    - assets/sounds/HighE.mp3
    - assets/sounds/B.mp3
    - assets/sounds/G.mp3
    - assets/sounds/D.mp3
    - assets/sounds/A.mp3
    - assets/sounds/LowE.mp3

    - assets/songs/Amara_Ya_Amara.mp3
    - assets/songs/creep.mp3
    - assets/songs/Estesna'i.mp3
    - assets/songs/Hotel_California.mp3
    - assets/songs/Law_Baddak_Yani.mp3
    - assets/songs/Nothing_Else_Matters.mp3
    - assets/songs/Shayef.mp3
    - assets/songs/Stairway_To_Heaven.mp3
    - assets/songs/Sweet_Child_O'_Mine.mp3
    - assets/songs/Wish_You_Were_Here.mp3

    - assets/chords/c.png
    - assets/chords/cm.png
    - assets/chords/c#m7.png
    - assets/chords/d.png
    - assets/chords/dm.png
    - assets/chords/e.png
    - assets/chords/em.png
    - assets/chords/e7.png
    - assets/chords/f.png
    - assets/chords/f#m.png
    - assets/chords/g.png
    - assets/chords/g#m.png
    - assets/chords/a.png
    - assets/chords/am.png
    - assets/chords/b.png
    - assets/chords/b7.png


# flutter run lib/main.dart -d chrome

# cd /Users/apple/LIU/Mobile/project1/backend && node server.js & cd /Users/apple/LIU/Mobile/project1/guitartuner && flutter run -d chrome


# if we want to update anything in our entry in our backend, we can use the following curl command by replacing the id and the fields to be updated:

# curl -X PUT http://localhost:5001/songs/6 \
#   -H "Content-Type: application/json" \
#   -d '{
#     "title": "Stairway to Heaven",
#     "artist": "Led Zeppelin", 
#     "chords": ["Am","C","D","F","G","Am","C","D","F","Am"],
#     "audioPath": "songs/Stairway_To_Heaven.mp3",
#     "isFavorite": false
#   }'


# test backend apis

# curl -s -X GET "http://localhost:5001/songs" | jq '.count'